{{ if eq (.Values.gcxi.deployment.useHostPathLogPV | default false) false }}
{{ if eq (.Values.gcxi.deployment.deployMain | default false) true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-log-pvc{{ template "deploymentCode" . }}
  namespace: {{ .Values.gcxi.app.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gcxi.pvc.log.capacity }}
  {{- if eq (.Values.gcxi.deployment.deployLocalPV | default false) true }}
  storageClassName: {{ .Values.gcxi.local.sc.name }}
  volumeName: gcxi-log-pv-local{{ template "deploymentCode" . }}
  {{- else }}
  storageClassName: {{ .Values.gcxi.pvc.log.storageClassName }}
  {{- if .Values.gcxi.pvc.log.volumeName }}
  volumeName: {{ .Values.gcxi.pvc.log.volumeName }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
