{{ if eq (.Values.gcxi.deployment.deployLocalPV | default false) true }}
{{ if eq (.Values.gcxi.deployment.deployMain | default false) true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-share-pv-local{{ template "deploymentCode" . }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.gcxi.local.pv.share.capacity }}
  local:
    path: {{ .Values.gcxi.local.pv.share.path }}/{{ include "deploymentCode" . | trimPrefix "-" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gcxi/local-pv-gcxi-share
          operator: In
          values:
          - "true"
  storageClassName: {{ .Values.gcxi.local.sc.name }}
{{- end }}
{{- end }}
