{{ if eq (.Values.gcxi.deployment.deployPostgres | default false) true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-postgres
  namespace: {{ .Values.gcxi.app.namespace }}
spec:
  ports:
  - name: db
    port: {{ .Values.gcxi.ports.postgres.db }}
  selector:
    gcxi/app: gcxi-postgres
  type: {{ .Values.gcxi.svc.postgres.type }}
{{- end }}
