{{ if eq (.Values.gcxi.deployment.deployMain | default false) true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
    genesysengage/monitoring: prometheus
  name: gcxi{{ template "deploymentCode" . }}
  namespace: {{ .Values.gcxi.app.namespace }}
spec:
  ports:
  {{- range $key, $value := .Values.gcxi.ports.worker }}
  - name: {{ $key }}
    port: {{ $value }}
  {{- end }}
  selector:
    gcxi/app: gcxi-worker{{ template "deploymentCode" . }}
  sessionAffinity: ClientIP
  type: {{ .Values.gcxi.svc.worker.type }}
{{- end }}
