{{- if .Values.gcxi.deployment.deployPrometheusRules -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
    genesysengage/monitoring: prometheus
  name: gcxi-alerts
  namespace: {{ .Values.gcxi.app.namespace }}
# https://github.com/kubernetes/kube-state-metrics/tree/master/docs
spec:
  groups:
  - name: gcxi-kube-state-metrics
    rules:
    - alert: gcxi-pod-pending
      expr: kube_pod_status_phase{namespace={{ .Values.gcxi.app.namespace | quote }}, phase="Pending", pod!~"gcxi-raa.*-"} > 0
      for: 15m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: warning
      annotations:
        description: Pod {{ "{{" }}$labels.pod}} is pending for 15 minutes.
        summary: GCXI Pod in Pending state

    - alert: gcxi-pod-start-fail
      expr: kube_pod_container_status_waiting_reason{namespace={{ .Values.gcxi.app.namespace | quote }}, reason!="ContainerCreating", pod!~"gcxi-raa.*-"} > 0
      for: 15m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: warning
      annotations:
        description: Pod {{ "{{" }}$labels.pod}} is failing to start with a reason {{ "{{" }}$labels.reason}}
        summary: GCXI Pod start fail

    - alert: gcxi-pod-terminated
      expr: kube_pod_container_status_terminated_reason{namespace={{ .Values.gcxi.app.namespace | quote }}, reason!="Completed", pod!~"gcxi-raa.*-"} > 0
      for: 10m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: warning
      annotations:
        description: Pod {{ "{{" }}$labels.pod}} terminated with a reason {{ "{{" }}$labels.reason}}
        summary: GCXI Pod terminated

    - alert: gcxi-job-fail
      expr: kube_job_status_failed{namespace={{ .Values.gcxi.app.namespace | quote }}, pod!~"gcxi-raa.*-"} > 0
      for: 1m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: warning
      annotations:
        description: Pod {{ "{{" }}$labels.pod}} job failed.
        summary: GCXI Job fail

  - name: cadvisor
    rules:
    - alert: gcxi-high-memory-usage
      expr: ((( sum(container_memory_usage_bytes{namespace={{ .Release.Namespace | quote }}}) by (container,pod)  / sum(container_spec_memory_limit_bytes{namespace={{ .Release.Namespace | quote }}}) by (container,pod) ) * 100 ) < +Inf ) > 80
      for: 15m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: info
      annotations: 
        description: Pod {{ "{{" }}$labels.pod}} is hitting Memory Limit.
        summary: GCXI Pod Memory Limit

  - name: nginx
    rules:
    - alert: gcxi-returns-5xx
      expr: ((sum(rate(nginx_ingress_controller_requests{ingress=~"gcxi-.*",status=~"5.*"}[15m])) by (exported_service) /
              sum(rate(nginx_ingress_controller_requests{ingress=~"gcxi-.*"}[15m])) by (exported_service))) > 0.2
      for: 10m
      labels:
        action: page
        service: gcxi
        servicename: gcxi
        severity: critical
      annotations: 
        description: Ingress {{ "{{" }}$labels.ingress}} returns 5xx.
        summary: GCXI 5xx

  - name: gcxi
    rules:
    - alert: gcxi-failed-reports
      expr: gcxi__projects__status{namespace={{ .Values.gcxi.app.namespace | quote }}} > 0
      for: 15m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: warning
      annotations: 
        description: Service {{ "{{" }}$labels.service}} shows test report failing.
        summary: GCXI Test Report Fail

    - alert: gcxi-cluster-disconnected
      expr: gcxi__cluster__info{namespace={{ .Values.gcxi.app.namespace | quote }}} != 2
      for: 15m
      labels:
        action: email
        service: gcxi
        servicename: gcxi
        severity: warning
      annotations: 
        description: Service {{ "{{" }}$labels.service}} shows test report failing.
        summary: GCXI Cluster Disconnected
{{- end }}
