{{ if eq (.Values.gcxi.deployment.deployMain | default false) true }}
{{- if .Values.gcxi.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: {{ .Values.gcxi.imageCredentials.name }}{{ template "deploymentCode" . }}
  namespace: {{ .Values.gcxi.app.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  ### Docker registry credentials ###
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
