{{ if eq (.Values.gcxi.deployment.deployMain | default false) true }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-secret-ext{{ template "deploymentCode" . }}
  namespace: {{ .Values.gcxi.app.namespace }}
type: Opaque
data:
  ### DSN (data source) properties: GIM and others ###

  ## secrets for DSN definitions aka DSNDEF
  ## variables must be named as '<DSN_NAME>__<VAR_NAME>'
  ## also legacy '<DSN_NAME>.<VAR_NAME>' is supported,
  ## but only if the secret is used as a secret mount (not passed as env)

  ## secrets for GCXI_GIM_DB DSN (connection to GIM database)
  {{- $var := .Values.gcxi.env.GCXI_GIM_DB.LOGIN }}
  {{- if $var }}
  GCXI_GIM_DB__LOGIN: {{ (tpl $var .) | b64enc }}
  {{- end }}

  {{- $var := .Values.gcxi.env.GCXI_GIM_DB.PASSWORD }}
  {{- if $var }}
  GCXI_GIM_DB__PASSWORD: {{ (tpl $var .) | b64enc }}
  {{- end }}

  ## secrets for IWD_DB DSN (connection to IWD database)
  {{- $var := .Values.gcxi.env.IWD_DB.LOGIN }}
  {{- if $var }}
  IWD_DB__LOGIN: {{ (tpl $var .) | b64enc }}
  {{- end }}

  {{- $var := .Values.gcxi.env.IWD_DB.PASSWORD }}
  {{- if $var }}
  IWD_DB__PASSWORD: {{ (tpl $var .) | b64enc }}
  {{- end }}

  ## secrets for extra DSNs (not GCXI_GIM_DB and IWD_DB)
  {{- range $def := .Values.gcxi.env.DSNDEFS }}
  {{- $var := $def.LOGIN }}
  {{- if $var }}
  {{ $def.NAME }}__LOGIN: {{ (tpl $var $) | b64enc }}
  {{- end }}
  {{- $var := $def.PASSWORD }}
  {{- if $var }}
  {{ $def.NAME }}__PASSWORD: {{ (tpl $var $) | b64enc }}
  {{- end }}
  {{- end }}
---
{{ if eq (.Values.gcxi.deployment.deploySecrets | default false) true }}
apiVersion: v1
kind: Secret
metadata:
  {{- if eq (.Values.gcxi.deployment.deployRandomSecrets | default false) true }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
  {{- end }}
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-secret{{ template "deploymentCode" . }}
  namespace: {{ .Values.gcxi.app.namespace }}
type: Opaque
data:
  ### Meta db non-admin users secrets ###
  ## db admin secrets moved to gcxi-secret-pg.yaml

  {{- $var := .Values.gcxi.env.META_DB_LOGIN }}
  {{- if $var }}
  META_DB_LOGIN: {{ (tpl $var .) | b64enc }}
  {{- end }}

  {{- $var := .Values.gcxi.env.META_HIST_LOGIN }}
  {{- if $var }}
  META_HIST_LOGIN: {{ (tpl $var .) | b64enc }}
  {{- end }}

  ### MSTR login secrets ###

  {{- $var := .Values.gcxi.env.MSTR_PASSWORD_OLD }}
  {{- if $var }}
  MSTR_PASSWORD_OLD: {{ (tpl $var .) | b64enc }}
  {{- end }}

  {{- $var := .Values.gcxi.env.META_DB_PASSWORD }}
  {{- if $var }}
  META_DB_PASSWORD: {{ (tpl $var .) | b64enc }}
  {{- else if eq (.Values.gcxi.deployment.deployRandomSecrets | default false) true }}
  META_DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}

  {{- $var := .Values.gcxi.env.META_HIST_PASSWORD }}
  {{- if $var }}
  META_HIST_PASSWORD: {{ (tpl $var .) | b64enc }}
  {{- else if eq (.Values.gcxi.deployment.deployRandomSecrets | default false) true }}
  META_HIST_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}

  {{- $var := .Values.gcxi.env.MSTR_LICENSE }}
  {{- if $var }}
  MSTR_LICENSE: {{ (tpl $var .) | b64enc }}
  {{- end }}

  {{- $var := .Values.gcxi.env.MSTR_PASSWORD }}
  {{- if $var }}
  MSTR_PASSWORD: {{ (tpl $var .) | b64enc }}
  {{- else if eq (.Values.gcxi.deployment.deployRandomSecrets | default false) true }}
  MSTR_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}

  {{- $var := .Values.gcxi.env.MSTR_TEST_PASSWORD }}
  {{- if $var }}
  MSTR_TEST_PASSWORD: {{ (tpl $var .) | b64enc }}
  {{- else if eq (.Values.gcxi.deployment.deployRandomSecrets | default false) true }}
  MSTR_TEST_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}

  {{- $var := .Values.gcxi.env.TOMCAT_ADMINPWD }}
  {{- if $var }}
  TOMCAT_ADMINPWD: {{ (tpl $var .) | b64enc }}
  {{- else if eq (.Values.gcxi.deployment.deployRandomSecrets | default false) true }}
  TOMCAT_ADMINPWD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
