{{ if eq (.Values.gcxi.deployment.deployLocalPV | default false) true }}
{{ if eq (.Values.gcxi.deployment.deployPostgres | default false) true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-postgres-pv-local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.gcxi.local.pv.postgres.capacity }}
  local:
    path: {{ .Values.gcxi.local.pv.postgres.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gcxi/local-pv-postgres-data
          operator: In
          values:
          - "true"
  storageClassName: {{ .Values.gcxi.local.sc.name }}
{{- end }}
{{- end }}
