{{ if eq (.Values.gcxi.deployment.deployMain | default false) true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-share-pvc{{ template "deploymentCode" . }}
  namespace: {{ .Values.gcxi.app.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.gcxi.pvc.share.capacity }}
  {{- if eq (.Values.gcxi.deployment.deployLocalPV | default false) true }}
  storageClassName: {{ .Values.gcxi.local.sc.name }}
  volumeName: gcxi-share-pv-local{{ template "deploymentCode" . }}
  {{- else }}
  storageClassName: {{ .Values.gcxi.pvc.share.storageClassName }}
  {{- if .Values.gcxi.pvc.share.volumeName }}
  volumeName: {{ .Values.gcxi.pvc.share.volumeName }}
  {{- end }}
  {{- end }}
{{- end }}
