{{ if eq (.Values.gcxi.deployment.deployPostgresConfig | default false) true }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "gcxi.labels" . | nindent 4 }}
  name: gcxi-secret-pg
  namespace: {{ .Values.gcxi.app.namespace }}
type: Opaque
data:
  ### Meta db properties ###

  ## GCXI meta db admin user secrets
  {{- $var := .Values.gcxi.env.META_DB_ADMIN }}
  {{- if $var }}
  META_DB_ADMIN: {{ $var | b64enc }}
  {{- end }}

  {{- $var := .Values.gcxi.env.META_DB_ADMINPWD }}
  {{- if $var }}
  META_DB_ADMINPWD: {{ $var | b64enc }}
  {{- end }}
{{- end }}
